In [1]:
import numpy as np

In [2]:
# creation of np array
x= np.array([1,2,3,4,5])
print(x)
print(type(x))  # ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# shape and size
print(x.size)  # total numbers of element
print(x.shape)  # dimension wise elements
print(x.ndim)   # numof dimensions


5
(5,)
1


In [4]:
x2d = np.array([[1,2,3],[4,5,6]])
print(x2d)
print(x2d.size)  # total numbers of element
print(x2d.shape)  # dimension wise elements
print(x2d.ndim)   # numof dimensions



[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [5]:
x25 = np.random.randint(1,100,(5,5))
print(x25)

[[31 86 67 32 47]
 [26 50 79  8 91]
 [26 75 78 36 24]
 [51 55 93 82 73]
 [15 18 90 96 52]]


In [6]:
xseq1 = np.arange(1,101,4)
print('1D MATRIX')
print(xseq1)
print(xseq1.size)
print('1D MATRIX RESHAPED TO 2D')
print(xseq1.reshape(5,5))

1D MATRIX
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25
1D MATRIX RESHAPED TO 2D
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [7]:
xseq2 = np.linspace(1,100,50)
print(xseq2.size,'element')
print('1D MATRIX')
print(xseq2)
print(xseq2.size)
print('1D MATRIX RESHAPED TO 2D')
print(xseq2.reshape(10,5))
print('1D MATRIX RESHAPED TO 3D')
print(xseq2.reshape(5,5,2))

50 element
1D MATRIX
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
50
1D MATRIX RESHAPED TO 2D
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.

xseq2d =
print(xseq2d)

In [8]:
np.ones((5,5),dtype ='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- indexing and slicing
- boolean filter
- maths and stats
- methods

In [9]:
x25

array([[31, 86, 67, 32, 47],
       [26, 50, 79,  8, 91],
       [26, 75, 78, 36, 24],
       [51, 55, 93, 82, 73],
       [15, 18, 90, 96, 52]])

In [10]:
# first row
print(x25[0])

[31 86 67 32 47]


In [11]:
#last row
print(x25[-1])

[15 18 90 96 52]


In [12]:
print(x25[0,1])  # same as print(x25[0][1])

86


In [13]:
#fisrt column
print(x25[:,0])

#2nd column
print(x25[:,1])

#last column
print(x25[:,-1])


[31 26 26 51 15]
[86 50 75 55 18]
[47 91 24 73 52]


In [14]:
print(x25[:,[0,1]])

[[31 86]
 [26 50]
 [26 75]
 [51 55]
 [15 18]]


In [15]:
print(x25[:,[0,1,2]])
print(x25[:, :3])

[[31 86 67]
 [26 50 79]
 [26 75 78]
 [51 55 93]
 [15 18 90]]
[[31 86 67]
 [26 50 79]
 [26 75 78]
 [51 55 93]
 [15 18 90]]


In [16]:
#filtering data without numpy boolean filter(bad idea)
for  i in x25:
    for j in i:
        if j <= 20:
            print(j)

8
15
18


In [17]:
x25[ x25 <= 20]

array([ 8, 15, 18])

In [18]:
x25[ x25 > 50]

array([86, 67, 79, 91, 75, 78, 51, 55, 93, 82, 73, 90, 96, 52])

In [19]:
(x25 > 20) & (x25 < 70)

array([[ True, False,  True,  True,  True],
       [ True,  True, False, False, False],
       [ True, False, False,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False,  True]])

In [20]:
x25[(x25 > 20 )& (x25 <70)]

array([31, 67, 32, 47, 26, 50, 26, 36, 24, 51, 55, 52])

In [21]:
np.append(x25, [1,2,3,4,5])   #not as expected but work

array([31, 86, 67, 32, 47, 26, 50, 79,  8, 91, 26, 75, 78, 36, 24, 51, 55,
       93, 82, 73, 15, 18, 90, 96, 52,  1,  2,  3,  4,  5])

In [22]:
np.append(x25, np.array([[1,2,3,5,6]]), axis=0)  


array([[31, 86, 67, 32, 47],
       [26, 50, 79,  8, 91],
       [26, 75, 78, 36, 24],
       [51, 55, 93, 82, 73],
       [15, 18, 90, 96, 52],
       [ 1,  2,  3,  5,  6]])

In [23]:
a= np.random.randint(1,100,(3,2))
b= np.random.randint(1,100,(2,3))

In [24]:
print(a.shape)
print(b.shape)


(3, 2)
(2, 3)


In [25]:
a.T

array([[ 8, 44, 40],
       [81,  9, 80]])

In [26]:
print(np.hstack((a,b.T)))

[[ 8 81 65  1]
 [44  9 43 17]
 [40 80 34 83]]


In [27]:
print(np.hstack((a.T,b)))


[[ 8 44 40 65 43 34]
 [81  9 80  1 17 83]]


In [28]:
print(np.vstack((a,b.T)))
print(np.vstack((a.T,b)))



[[ 8 81]
 [44  9]
 [40 80]
 [65  1]
 [43 17]
 [34 83]]
[[ 8 44 40]
 [81  9 80]
 [65 43 34]
 [ 1 17 83]]


In [29]:
print(x.mean())  # all


3.0


In [30]:
print(x.max())    # max value
print(x.min())    # min value
print(x.argmax()) # index of max value
print(x.argmin()) # index of min value
print(x.flatten()[4])  # accessing the index value given by argmax()

5
1
4
0
5


In [31]:
np.median(x)  # some function are called using 

3.0